### PR TITLE
Trying to det docz2 working

### PR DESCRIPTION
**Pull request by geelen**

### CODE REVIEW

**Comment by sw-yx** [comment]
what wasnt working? cc @pedronauck

**Comment by geelen** [comment]
No idea. Getting a gatsby 404 helper page in `docz:dev`, build failures both locally and on Linc. I think I should generate a brand new docz project now v2 is out and then gradually include each module one by one. Will do that in this branch.

**Comment by pedronauck** [comment]
@rakannimer can you help @geelen on this?

**Comment by rakannimer** [comment]
@pedronauck for sure, @geelen I'll start from `fab-cli` or `docz-fixes` ?

**Comment by geelen** [comment]
Thanks for the help!

Work on `docz-fixes`. I reverted to v1 on `fab-cli` so don't worry if there's merge conflicts in this PR, I'll resolve them if we can get v2 working again.

Added you as a collaborator so you can just push to this branch directly, that way Linc will deploy each commit so we can make sure it's all good 👍

**Comment by geelen** [comment]
Currently, the error is `error You have an empty file in the "src/pages" directory at "../../packages/rewire-assets/README.md". Please remove it or make it a valid component` on Linc, but I was getting something different locally.

**Comment by rakannimer** [comment]
Hey 

I wrote a fix but I can't push to `docz-fixes`, I'm getting : 

```
ERROR: Permission to fab-spec/fab.git denied to rakannimer.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any idea why ? Meanwhile I can PR to `docz-fixes`

**Comment by rakannimer** [comment]
There are 3 possible ways I can think of to solve the issue :

1. That's the one in this PR: moving docz to the root of the repo.

2. Moving the docs folder inside packages so it can share node_modules with the rest of fab packages.

3. Leaving the docs folder setup as it is and configuring webpack to look for dependencies in both /node_modules and /docs/node_modules.

I went with 1 because it seemed like the easiest one.

Do you have any preference ?


I think linc is still failing because it's looking for a package.json in `docs/package.json` as shown in the pic below. Could you change it to `package.json` ?
Screen Shot 2019-12-04 at 9 57 12 PM

**Comment by geelen** [comment]
This is great. I'll get it merged.

**Pull request merged**
