### PR TITLE
potential implementation

### PR DESCRIPTION
**Pull request by Jarvis1010**
I am probably pretty stupid but I am at a loss of how to test this to see if it works.  From what I understand, `tsc` will look for the closest tsconfig up the file system, so I am not sure how to recreate that.  Not sure this PR will help, I am pretty sure it wont hurt.

### CODE REVIEW

**Comment by geelen** [comment]
Hmm, yeah this looks like a good solution, but I'm a bit confused why that test would be failing:

https://github.com/fab-spec/fab/pull/201/checks?check_run_id=838191862#step:7:220

It's in `packages/actions`, I'm guessing it's forking off a copy of `tsc` in the background and hanging Jest?

**Comment by Jarvis1010** [comment]
Maybe because it’s a draft PR?

**Comment by Jarvis1010** [comment]
wow, that's crazy!  Thank you, Michael Jackson, for showing us the way.

**Comment by geelen** [comment]
Just doing some manual testing on this, something's not quite right :)

image

**Comment by Jarvis1010** [comment]
That is odd, why would it output the --help?  I am using version 3.9.5 on my machine, but that shouldn't be a reason

**Comment by geelen** [comment]
Ok I dug into it, it was running `tsc --noEmit` in your local directory, but not actually typechecking the plugins that were passed in. So it would use the `tsconfig` to find the source directory and check that, etc.

I've just reworked it to pass the runtime plugins list to `tsc`, so it'll no longer be checking the whole directory, just the files you reference. It's kinda slow on small projects so I'm running it off in the background. Also made it so errors are treated as warnings by default (since I'm not sure this is going to work for everyone just yet) unless `CI=true` is set, and if it's too slow/broken I've added a `--skip-typecheck` flag to `fab build` to skip it.

Will roll this into a new RC once #198 is done.

**Comment by Jarvis1010** [comment]
That was what I was afraid of. The full fleshed our version makes a lot of sense. Thanks for finishing my incomplete thought

**Comment by geelen** [comment]
Ugh, this is what _I_ was afraid of. Weird type errors that have nothing to do with the plugins you're writing, but are about your environment being broken (in this case, my E2E tests use Jest but the individual packages tests use Mocha, cause of Oclif).

So I might pause this until I have a chance to move all the per-package tests to Jest (which, to be fair, there aren't many of, so I should maybe write some extra tests there or delete the ones that aren't providing value...)

**Comment by Jarvis1010** [comment]
What would be nice if there was a way to pass files and/or regex to exclude at the command line.  As far as I can tell, that is only available with the tsconfig

**Comment by geelen** [comment]
Actually I wonder if we should go the opposite way: make a `tsconfig.json` file in a temporary directory (or within the unpacked `node_modules/@fab/actions` directory somewhere) that gives all the relevant definitions. Hmm...

**Comment by geelen** [comment]
@Jarvis1010 this is kinda slow, and I'm not 100% sure it won't break for non-trivial plugins, but I think I can live with it being on by default for a while (you can use `--skip-typecheck` if needed). If I've misunderstood how it ought to work I'll wind it back to opt-in rather than opt-out, or use the bug reports to understand how this should work a bit deeper.

As it is, though, it should help you catch type errors when you write a simple plugin, which I think makes the new-user experience better for everyone. Thanks for kicking this off!

**Comment by Jarvis1010** [comment]
Thanks for the opportunity.  Enjoy working on this project from time to time

**Pull request merged**
